services:
  - type: web
    name: whatsapp-automator-server
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MAX_SESSIONS
        value: 20
      - key: SESSION_TIMEOUT_MINUTES
        value: 45
      - key: CLEANUP_INTERVAL_MINUTES
        value: 10
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 200
      - key: LOG_LEVEL
        value: info
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: whatsapp-data
      mountPath: /opt/render/project/src/data
      sizeGB: 10 